require 'open-uri'

pages = [
    [ ".NET-Framework", ".NET Framework" ],
    [ ".NET-IoC-Containers", ".NET IoC Containers" ],
    [ ".NET-Tips", ".NET Tips" ],
    [ ".NET-Tools", ".NET Tools" ],
    [ "Agile-Estimates", "Agile Estimates" ],
    [ "Algorithms", "Algorithms" ],
    [ "Architecture", "Architecture" ],
    [ "Automated-Testing", "Automated Testing" ],
    [ "Binary-Search", "Binary Search" ],
    [ "Books", "Books" ],
    [ "C-Sharp", "C Sharp" ],
    [ "Caching", "Caching" ],
    [ "CAP-Theorem", "CAP Theorem" ],
    [ "Checklists", "Checklists" ],
    [ "Code-Contracts", "Code Contracts" ],
    [ "Comment-Driven-Design", "Comment Driven Design" ],
    [ "Comments", "Comments" ],
    [ "Complex-Event-Processing", "Complex Event Processing" ],
    [ "Concurrency", "Concurrency" ],
    [ "Consistency", "Consistency" ],
    [ "Continuous-Delivery-Practices", "Continuous Delivery Practices" ],
    [ "CSP", "CSP" ],
    [ "Data-Structures", "Data Structures" ],
    [ "Databases", "Databases" ],
    [ "Design", "Design" ],
    [ "DevOps", "DevOps" ],
    [ "Docker", "Docker" ],
    [ "Docker-Compose", "Docker Compose" ],
    [ "Encoding-Data", "Encoding Data" ],
    [ "Errors", "Errors" ],
    [ "Essential-and-accidental-complexity", "Essential and accidental complexity" ],
    [ "Estimates", "Estimates" ],
    [ "Excel", "Excel" ],
    [ "F-Sharp", "F Sharp" ],
    [ "Getting-stuff-done", "Getting stuff done" ],
    [ "Git", "Git" ],
    [ "Go", "Go" ],
    [ "Guidance", "Guidance" ],
    [ "Hash-table", "Hash table" ],
    [ "Ideal-Operating-System", "Ideal Operating System" ],
    [ "IIS", "IIS" ],
    [ "Inheritance-Rules", "Inheritance Rules" ],
    [ "Java", "Java" ],
    [ "JSON", "JSON" ],
    [ "Layers", "Layers" ],
    [ "Management", "Management" ],
    [ "Mapping", "Mapping" ],
    [ "Measuring-Software-Delivery-Performance", "Measuring Software Delivery Performance" ],
    [ "Messaging", "Messaging" ],
    [ "Messaging-patterns-for-MSMQ", "Messaging patterns for MSMQ" ],
    [ "Microservice-architecture", "Microservice architecture" ],
    [ "Modern-CPU-design", "Modern CPU design" ],
    [ "Modules", "Modules" ],
    [ "Monitoring", "Monitoring" ],
    [ "MSMQ", "MSMQ" ],
    [ "Natural-state", "Natural state" ],
    [ "Nature-of-complexity", "Nature of complexity" ],
    [ "NuGet", "NuGet" ],
    [ "Obvious", "Obvious" ],
    [ "Performance-reviews", "Performance reviews" ],
    [ "Problem-Solving", "Problem Solving" ],
    [ "Process-abstraction", "Process abstraction" ],
    [ "Programming-History", "Programming History" ],
    [ "Rob-Pike's-6-rules-of-programming", "Rob Pike's 6 rules of programming" ],
    [ "Simple-is-not-easy", "Simple is not easy" ],
    [ "Software-developer-rules", "Software developer rules" ],
    [ "Solace-Messaging", "Solace Messaging" ],
    [ "SQL-Server", "SQL Server" ],
    [ "State-machines", "State machines" ],
    [ "Strategic-verses-tactial", "Strategic verses tactial" ],
    [ "Sustainable-software-development", "Sustainable software development" ],
    [ "Talks", "Talks" ],
    [ "Testing", "Testing" ],
    [ "Theory-Building", "Theory Building" ],
    [ "Visual-Studio", "Visual Studio" ],
    [ "WebAssembly", "WebAssembly" ],
    [ "Weekly-learnings", "Weekly learnings" ],
    [ "WinDbg", "WinDbg" ],
]

pages.each do |pair|
    puts pair[0]
    open("./#{pair[0]}.md", "w") do |file|
        file << "---\n"
        file << "title: \"#{pair[1]}\"\n"
        file << "---\n"
        file << "# #{pair[1]}\n\n"
        file << open("https://github.com/busterwood/wiki/wiki/#{pair[0]}.md").read 
    end
end